name: Lint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: "**/*.py"

      - name: Black formatter
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        uses: psf/black@25.9.0
        with:
          src: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Ruff linter
        if: ${{ steps.changed-files.outputs.all_changed_files != '' }}
        uses: chartboost/ruff-action@v1
        with:
          src: ${{ steps.changed-files.outputs.all_changed_files }}
