name: Run Python Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    paths:
      - '**/*.py'
      - '**/requirements.txt'

jobs:
  list-tests:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.list-dirs.outputs.dirs }}
    steps:
    - uses: actions/checkout@v5
    - id: list-dirs
      run: |
        dirs="["
        for d in tests/*/; 
        do
          d_name=$(basename "$d")
          if [ -n "$dirs" ] && [ "$dirs" != "[" ]; then
            dirs="$dirs,"
          fi
          dirs="$dirs\"$d_name\""
        done
        dirs="$dirs]"
        echo "dirs=$dirs" >> $GITHUB_OUTPUT

  test:
    needs: list-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script_dir: ${{ fromJson(needs.list-tests.outputs.dirs) }}

    steps:
    - uses: actions/checkout@v5

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v46
      with:
        files: |
          ${{ matrix.script_dir }}/**

    - name: Set up Python
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        if [ -f "${{ matrix.script_dir }}/requirements.txt" ]; then
          pip install -r "${{ matrix.script_dir }}/requirements.txt"
        fi

    - name: Test with pytest
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        pytest tests/${{ matrix.script_dir }}