name: Run Python Tests

on:
  pull_request:
    paths:
      - '**/*.py'
      - '**/requirements.txt'
  workflow_dispatch:

jobs:
  list-tests:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.list-dirs.outputs.dirs }}
    steps:
    - uses: actions/checkout@v5
    - id: list-dirs
      run: echo "dirs=$(ls -d tests/*/ | xargs -n 1 basename | jq -R . | jq -s .)" >> $GITHUB_OUTPUT

  test:
    needs: list-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script_dir: ${{ fromJson(needs.list-tests.outputs.dirs) }}

    steps:
    - uses: actions/checkout@v5

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v46
      with:
        files: |
          ${{ matrix.script_dir }}/**

    - name: Set up Python
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements.txt
        if [ -f "${{ matrix.script_dir }}/requirements.txt" ]; then
          pip install -r "${{ matrix.script_dir }}/requirements.txt"
        fi

    - name: Test with pytest
      if: steps.changed-files.outputs.any_changed == 'true'
      run: |
        pytest tests/${{ matrix.script_dir }}
